In [1]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

In [ ]:
CLIENT_ID = "Your Client ID"
CLIENT_SECRET = "Your Client Secret"

auth_manager = SpotifyClientCredentials(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET
)

sp = spotipy.Spotify(auth_manager=auth_manager)

print("Connected Successfully")

Connected Successfully

*Extracting Artist Details*

In [ ]:
artists = ["Taylor Swift", "Drake", "Coldplay", "The Weeknd"]

artist_list = []
for artist_name in artists:
    data = sp.search(q=artist_name, type='artist', limit=None)
    artist = data['artists']['items'][0]
    
    artist_data = {
        'artist_id': artist['id'],
        'artist_name': artist['name'],
        'spotify_url': artist['external_urls']['spotify'],
        'artist_image_url': artist['images'][0]['url'] if artist['images'] else None,
        'uri': artist['uri']
    }
    artist_list.append(artist_data)
    print(f"✅ {artist['name']} — ID: {artist['id']}")

print(f"\nTotal artists fetched: {len(artist_list)}")

✅ Taylor Swift — ID: 06HL4z0CvFAxyc27GXpf02
✅ Drake — ID: 3TVXtAsR1Inumwj472S9r4
✅ Coldplay — ID: 4gzpq5DPGxSnKTe4SA8HAU
✅ The Weeknd — ID: 1Xyo4u8uXC1ZmMpatF05PJ

Total artists fetched: 4

In [19]:
type(data)

dict

In [22]:
artist_data.keys()

dict_keys(['artist_id', 'artist_name', 'spotify_url', 'artist_image_url', 'uri'])

In [25]:
artist_list

[{'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift',
  'spotify_url': 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02',
  'artist_image_url': 'https://i.scdn.co/image/ab6761610000e5ebe2e8e7ff002a4afda1c7147e',
  'uri': 'spotify:artist:06HL4z0CvFAxyc27GXpf02'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'spotify_url': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4',
  'artist_image_url': 'https://i.scdn.co/image/ab6761610000e5eb4293385d324db8558179afd9',
  'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay',
  'spotify_url': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU',
  'artist_image_url': 'https://i.scdn.co/image/ab6761610000e5eb1ba8fc5f5c73e7e9313cc6eb',
  'uri': 'spotify:artist:4gzpq5DPGxSnKTe4SA8HAU'},
 {'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd',
  'spotify_url': 'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_image_url': 'https://i.scdn.co/image/ab6761610000e5ebc1719ac9e6a75c1c25835018',
  'uri': 'spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ'}]

In [27]:
import pandas as pd
artist_df = pd.DataFrame(artist_list)
artist_df.head()

,artist_id,artist_name,spotify_url,artist_image_url,uri
0,06HL4z0CvFAxyc27GXpf02,Taylor Swift,https://open.spotify.com/artist/06HL4z0CvFAxyc...,https://i.scdn.co/image/ab6761610000e5ebe2e8e7...,spotify:artist:06HL4z0CvFAxyc27GXpf02
1,3TVXtAsR1Inumwj472S9r4,Drake,https://open.spotify.com/artist/3TVXtAsR1Inumw...,https://i.scdn.co/image/ab6761610000e5eb429338...,spotify:artist:3TVXtAsR1Inumwj472S9r4
2,4gzpq5DPGxSnKTe4SA8HAU,Coldplay,https://open.spotify.com/artist/4gzpq5DPGxSnKT...,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...,spotify:artist:4gzpq5DPGxSnKTe4SA8HAU
3,1Xyo4u8uXC1ZmMpatF05PJ,The Weeknd,https://open.spotify.com/artist/1Xyo4u8uXC1ZmM...,https://i.scdn.co/image/ab6761610000e5ebc1719a...,spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ

In [28]:
artist_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   artist_id         4 non-null      str
 1   artist_name       4 non-null      str
 2   spotify_url       4 non-null      str
 3   artist_image_url  4 non-null      str
 4   uri               4 non-null      str
dtypes: str(5)
memory usage: 292.0 bytes

*Extracting Albums Deatils*

In [11]:
album_list = []
for artist in artist_list:
    results = sp.artist_albums(artist['artist_id'], album_type='album', limit=None)
    
    for album in results['items']:
        album_data = {
            'album_id': album['id'],
            'album_name': album['name'],
            'album_type': album['album_type'],
            'total_tracks': album['total_tracks'],
            'release_date': album['release_date'],
            'spotify_url': album['external_urls']['spotify'],
            'album_image_url': album['images'][0]['url'] if album['images'] else None,
            'artist_id': artist['artist_id'],
            'artist_name': artist['artist_name']
        }
        album_list.append(album_data)
    
    print(f"✅ {artist['artist_name']} — {len(results['items'])} albums fetched!")

print(f"\nTotal albums fetched: {len(album_list)}")

✅ Taylor Swift — 5 albums fetched!
✅ Drake — 5 albums fetched!
✅ Coldplay — 5 albums fetched!
✅ The Weeknd — 5 albums fetched!

Total albums fetched: 20

In [24]:
album_list

[{'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'album_type': 'album',
  'total_tracks': 19,
  'release_date': '2025-11-07',
  'spotify_url': 'https://open.spotify.com/album/6QNMhoV8V0u7cFuhhUBOn7',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273f756bdc2c11a985dc0c06d94',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'album_type': 'album',
  'total_tracks': 12,
  'release_date': '2025-10-03',
  'spotify_url': 'https://open.spotify.com/album/4a6NzYL1YHRUgx9e3YZI6I',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273d7812467811a7da6e6a44902',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'album_type': 'album',
  'total_tracks': 26,
  'release_date': '2025-10-02',
  'spotify_url': 'https://open.spotify.com/album/4tFsJC9jQ0Qjj7HSExhAdm',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b2737e0698e1398b6473de43f901',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'album_id': '5H7ixXZfsNMGbIE5OBSpcb',
  'album_name': 'THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY',
  'album_type': 'album',
  'total_tracks': 31,
  'release_date': '2024-04-19',
  'spotify_url': 'https://open.spotify.com/album/5H7ixXZfsNMGbIE5OBSpcb',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b2738ecc33f195df6aa257c39eaa',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'album_id': '1Mo4aZ8pdj6L1jx8zSwJnt',
  'album_name': 'THE TORTURED POETS DEPARTMENT',
  'album_type': 'album',
  'total_tracks': 16,
  'release_date': '2024-04-18',
  'spotify_url': 'https://open.spotify.com/album/1Mo4aZ8pdj6L1jx8zSwJnt',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b2735076e4160d018e378f488c33',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'album_id': '0OAv7DCME2AV4q1KPO95HY',
  'album_name': 'ICEMAN',
  'album_type': 'album',
  'total_tracks': 18,
  'release_date': '2026-05-15',
  'spotify_url': 'https://open.spotify.com/album/0OAv7DCME2AV4q1KPO95HY',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273fe9d3ab9adb1d3b59835b81c',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake'},
 {'album_id': '71yBvOeRZ9os9LYFEy9eOk',
  'album_name': 'MAID OF HONOUR',
  'album_type': 'album',
  'total_tracks': 14,
  'release_date': '2026-05-15',
  'spotify_url': 'https://open.spotify.com/album/71yBvOeRZ9os9LYFEy9eOk',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273539bb112d7c970545dd971e3',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake'},
 {'album_id': '0P6B5R3yRSkhkmequL5Yno',
  'album_name': 'HABIBTI',
  'album_type': 'album',
  'total_tracks': 11,
  'release_date': '2026-05-15',
  'spotify_url': 'https://open.spotify.com/album/0P6B5R3yRSkhkmequL5Yno',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273b92879e45761d711016476df',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake'},
 {'album_id': '6Rl6YoCarF2GHPSQmmFjuR',
  'album_name': '$ome $exy $ongs 4 U',
  'album_type': 'album',
  'total_tracks': 21,
  'release_date': '2025-02-14',
  'spotify_url': 'https://open.spotify.com/album/6Rl6YoCarF2GHPSQmmFjuR',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273b5a28a256eae6dc0424fef59',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake'},
 {'album_id': '4Q7cRXio6mF2ImVUCcezPO',
  'album_name': 'For All The Dogs Scary Hours Edition',
  'album_type': 'album',
  'total_tracks': 29,
  'release_date': '2023-11-17',
  'spotify_url': 'https://open.spotify.com/album/4Q7cRXio6mF2ImVUCcezPO',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273e286ee36b4015afa8832356a',
  'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake'},
 {'album_id': '5SGtrmYbIo0Dsg4kJ4qjM6',
  'album_name': 'Moon Music',
  'album_type': 'album',
  'total_tracks': 10,
  'release_date': '2024-10-04',
  'spotify_url': 'https://open.spotify.com/album/5SGtrmYbIo0Dsg4kJ4qjM6',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273f40306925074cfdcd8bee61f',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay'},
 {'album_id': '1PdMoahMiMnqWfzWZs3xSI',
  'album_name': 'Moon Music (Full Moon Edition)',
  'album_type': 'album',
  'total_tracks': 20,
  'release_date': '2024-10-03',
  'spotify_url': 'https://open.spotify.com/album/1PdMoahMiMnqWfzWZs3xSI',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273d75f119409f50e08ce77c5f1',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay'},
 {'album_id': '06mXfvDsRZNfnsGZvX2zpb',
  'album_name': 'Music Of The Spheres',
  'album_type': 'album',
  'total_tracks': 12,
  'release_date': '2021-10-15',
  'spotify_url': 'https://open.spotify.com/album/06mXfvDsRZNfnsGZvX2zpb',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273d5d34557fa33c03782d3e730',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay'},
 {'album_id': '2FeyIYDDAQqcOJKOKhvHdr',
  'album_name': 'Everyday Life',
  'album_type': 'album',
  'total_tracks': 16,
  'release_date': '2019-11-22',
  'spotify_url': 'https://open.spotify.com/album/2FeyIYDDAQqcOJKOKhvHdr',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273722d16eb3b31fae9cb1d2ada',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay'},
 {'album_id': '19CvkGjYpifkdwgVJSbog2',
  'album_name': 'Live in Buenos Aires',
  'album_type': 'album',
  'total_tracks': 24,
  'release_date': '2018-12-07',
  'spotify_url': 'https://open.spotify.com/album/19CvkGjYpifkdwgVJSbog2',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273fe5f1f4d742869a253036971',
  'artist_id': '4gzpq5DPGxSnKTe4SA8HAU',
  'artist_name': 'Coldplay'},
 {'album_id': '3OxfaVgvTxUTy7276t7SPU',
  'album_name': 'Hurry Up Tomorrow',
  'album_type': 'album',
  'total_tracks': 22,
  'release_date': '2025-01-31',
  'spotify_url': 'https://open.spotify.com/album/3OxfaVgvTxUTy7276t7SPU',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273de79f330bc297af3fae736da',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd'},
 {'album_id': '35dut3ICqF3NEDkjxfzJJ1',
  'album_name': 'Starboy (Deluxe)',
  'album_type': 'album',
  'total_tracks': 21,
  'release_date': '2023-03-14',
  'spotify_url': 'https://open.spotify.com/album/35dut3ICqF3NEDkjxfzJJ1',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b2738ad8f5243d6534e03b656c8b',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd'},
 {'album_id': '1OARrXe5sB0gyy3MhQ8h92',
  'album_name': 'Live At SoFi Stadium',
  'album_type': 'album',
  'total_tracks': 31,
  'release_date': '2023-03-03',
  'spotify_url': 'https://open.spotify.com/album/1OARrXe5sB0gyy3MhQ8h92',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273308f9319a3d6f6737f43b3fc',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd'},
 {'album_id': '12INlMsFtBjyehNnawBv36',
  'album_name': 'Dawn FM (Alternate World)',
  'album_type': 'album',
  'total_tracks': 24,
  'release_date': '2022-01-07',
  'spotify_url': 'https://open.spotify.com/album/12INlMsFtBjyehNnawBv36',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b273ade87e5f9c3764f0a1e5df64',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd'},
 {'album_id': '2nLOHgzXzwFEpl62zAgCEC',
  'album_name': 'Dawn FM',
  'album_type': 'album',
  'total_tracks': 16,
  'release_date': '2022-01-06',
  'spotify_url': 'https://open.spotify.com/album/2nLOHgzXzwFEpl62zAgCEC',
  'album_image_url': 'https://i.scdn.co/image/ab67616d0000b2734ab2520c2c77a1d66b9ee21d',
  'artist_id': '1Xyo4u8uXC1ZmMpatF05PJ',
  'artist_name': 'The Weeknd'}]

In [29]:
album_df = pd.DataFrame(album_list)
album_df.head()

,album_id,album_name,album_type,total_tracks,release_date,spotify_url,album_image_url,artist_id,artist_name
0,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,album,19,2025-11-07,https://open.spotify.com/album/6QNMhoV8V0u7cFu...,https://i.scdn.co/image/ab67616d0000b273f756bd...,06HL4z0CvFAxyc27GXpf02,Taylor Swift
1,4a6NzYL1YHRUgx9e3YZI6I,The Life of a Showgirl,album,12,2025-10-03,https://open.spotify.com/album/4a6NzYL1YHRUgx9...,https://i.scdn.co/image/ab67616d0000b273d78124...,06HL4z0CvFAxyc27GXpf02,Taylor Swift
2,4tFsJC9jQ0Qjj7HSExhAdm,The Life of a Showgirl (Track by Track Version),album,26,2025-10-02,https://open.spotify.com/album/4tFsJC9jQ0Qjj7H...,https://i.scdn.co/image/ab67616d0000b2737e0698...,06HL4z0CvFAxyc27GXpf02,Taylor Swift
3,5H7ixXZfsNMGbIE5OBSpcb,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,album,31,2024-04-19,https://open.spotify.com/album/5H7ixXZfsNMGbIE...,https://i.scdn.co/image/ab67616d0000b2738ecc33...,06HL4z0CvFAxyc27GXpf02,Taylor Swift
4,1Mo4aZ8pdj6L1jx8zSwJnt,THE TORTURED POETS DEPARTMENT,album,16,2024-04-18,https://open.spotify.com/album/1Mo4aZ8pdj6L1jx...,https://i.scdn.co/image/ab67616d0000b2735076e4...,06HL4z0CvFAxyc27GXpf02,Taylor Swift

In [30]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   album_id         20 non-null     str
 1   album_name       20 non-null     str
 2   album_type       20 non-null     str
 3   total_tracks     20 non-null     int64
 4   release_date     20 non-null     str
 5   spotify_url      20 non-null     str
 6   album_image_url  20 non-null     str
 7   artist_id        20 non-null     str
 8   artist_name      20 non-null     str
dtypes: int64(1), str(8)
memory usage: 1.5 KB

In [31]:
#converting release_date to datetime
album_df['release_date'] = pd.to_datetime(album_df['release_date'], errors = 'coerce')

In [32]:
album_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   album_id         20 non-null     str
 1   album_name       20 non-null     str
 2   album_type       20 non-null     str
 3   total_tracks     20 non-null     int64
 4   release_date     20 non-null     datetime64[us]
 5   spotify_url      20 non-null     str
 6   album_image_url  20 non-null     str
 7   artist_id        20 non-null     str
 8   artist_name      20 non-null     str
dtypes: datetime64[us](1), int64(1), str(7)
memory usage: 1.5 KB

In [40]:
album_df.isnull().sum()

album_id           0
album_name         0
album_type         0
total_tracks       0
release_date       0
spotify_url        0
album_image_url    0
artist_id          0
artist_name        0
dtype: int64

*Extracting Song Details*

In [ ]:
song_list = []
for album in album_list:
    data = sp.album_tracks(album['album_id'], limit=50)
    
    for track in data['items']:
        song_data = {
            'song_id': track['id'],
            'song_name': track['name'],
            'duration_ms': track['duration_ms'],
            'track_number': track['track_number'],
            'disc_number': track['disc_number'],
            'explicit': track['explicit'],
            'spotify_url': track['external_urls']['spotify'],
            'uri': track['uri'],
            'album_id': album['album_id'],
            'album_name': album['album_name'],
            'artist_id': album['artist_id'],
            'artist_name': album['artist_name']
        }
        song_list.append(song_data)
    
    print(f"✅ {album['album_name']} — {len(results['items'])} songs fetched!")

print(f"\nTotal songs fetched: {len(song_list)}")

✅ The Life of a Showgirl + Acoustic Collection — 19 songs fetched!
✅ The Life of a Showgirl — 12 songs fetched!
✅ The Life of a Showgirl (Track by Track Version) — 26 songs fetched!
✅ THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY — 31 songs fetched!
✅ THE TORTURED POETS DEPARTMENT — 16 songs fetched!
✅ ICEMAN — 18 songs fetched!
✅ MAID OF HONOUR — 14 songs fetched!
✅ HABIBTI — 11 songs fetched!
✅ $ome $exy $ongs 4 U — 21 songs fetched!
✅ For All The Dogs Scary Hours Edition — 29 songs fetched!
✅ Moon Music — 10 songs fetched!
✅ Moon Music (Full Moon Edition) — 20 songs fetched!
✅ Music Of The Spheres — 12 songs fetched!
✅ Everyday Life — 16 songs fetched!
✅ Live in Buenos Aires — 24 songs fetched!
✅ Hurry Up Tomorrow — 22 songs fetched!
✅ Starboy (Deluxe) — 21 songs fetched!
✅ Live At SoFi Stadium — 31 songs fetched!
✅ Dawn FM (Alternate World) — 24 songs fetched!
✅ Dawn FM — 16 songs fetched!

Total songs fetched: 393

In [33]:
song_list

[{'song_id': '5UQ3JrA9kEh7rfwhUS1h0z',
  'song_name': 'The Fate of Ophelia',
  'duration_ms': 226073,
  'track_number': 1,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/5UQ3JrA9kEh7rfwhUS1h0z',
  'uri': 'spotify:track:5UQ3JrA9kEh7rfwhUS1h0z',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6virCtlwc98cKYVyeZYXqq',
  'song_name': 'Elizabeth Taylor',
  'duration_ms': 208291,
  'track_number': 2,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/6virCtlwc98cKYVyeZYXqq',
  'uri': 'spotify:track:6virCtlwc98cKYVyeZYXqq',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '0WUwHkIXQY55MLOrw8EM6m',
  'song_name': 'Opalite',
  'duration_ms': 235356,
  'track_number': 3,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/0WUwHkIXQY55MLOrw8EM6m',
  'uri': 'spotify:track:0WUwHkIXQY55MLOrw8EM6m',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6H0nEKqkTRxa30Pru1h7SD',
  'song_name': 'Father Figure',
  'duration_ms': 212777,
  'track_number': 4,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6H0nEKqkTRxa30Pru1h7SD',
  'uri': 'spotify:track:6H0nEKqkTRxa30Pru1h7SD',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6nhsv9Jeluz5gXt592KN3m',
  'song_name': 'Eldest Daughter',
  'duration_ms': 246356,
  'track_number': 5,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6nhsv9Jeluz5gXt592KN3m',
  'uri': 'spotify:track:6nhsv9Jeluz5gXt592KN3m',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '05VwM318oU6aNc1GS4MtLV',
  'song_name': 'Ruin The Friendship',
  'duration_ms': 220564,
  'track_number': 6,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/05VwM318oU6aNc1GS4MtLV',
  'uri': 'spotify:track:05VwM318oU6aNc1GS4MtLV',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6G3dUZrsaOYhe2gRyNukwA',
  'song_name': 'Actually Romantic',
  'duration_ms': 163699,
  'track_number': 7,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6G3dUZrsaOYhe2gRyNukwA',
  'uri': 'spotify:track:6G3dUZrsaOYhe2gRyNukwA',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6udRZQi3g501XNOcRnE9fo',
  'song_name': 'Wi$h Li$t',
  'duration_ms': 207349,
  'track_number': 8,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6udRZQi3g501XNOcRnE9fo',
  'uri': 'spotify:track:6udRZQi3g501XNOcRnE9fo',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '4Ox858TeUXjy7WEKOcxaFI',
  'song_name': 'Wood',
  'duration_ms': 150517,
  'track_number': 9,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/4Ox858TeUXjy7WEKOcxaFI',
  'uri': 'spotify:track:4Ox858TeUXjy7WEKOcxaFI',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '67SmofYg9enUWfcPqUuoVm',
  'song_name': 'CANCELLED!',
  'duration_ms': 211498,
  'track_number': 10,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/67SmofYg9enUWfcPqUuoVm',
  'uri': 'spotify:track:67SmofYg9enUWfcPqUuoVm',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '7jHzBmxAGVVPvLiq4Y45pD',
  'song_name': 'Honey',
  'duration_ms': 181534,
  'track_number': 11,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/7jHzBmxAGVVPvLiq4Y45pD',
  'uri': 'spotify:track:7jHzBmxAGVVPvLiq4Y45pD',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6EqHzZp61G5uQ12QEiibpT',
  'song_name': 'The Life of a Showgirl (feat. Sabrina Carpenter)',
  'duration_ms': 241766,
  'track_number': 12,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6EqHzZp61G5uQ12QEiibpT',
  'uri': 'spotify:track:6EqHzZp61G5uQ12QEiibpT',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '3lcWDG62OH0cH5GHLdT5X4',
  'song_name': 'The Fate of Ophelia - Alone In My Tower Acoustic Version',
  'duration_ms': 225816,
  'track_number': 13,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/3lcWDG62OH0cH5GHLdT5X4',
  'uri': 'spotify:track:3lcWDG62OH0cH5GHLdT5X4',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '4UBWugj5D20ZveyzdGpqvD',
  'song_name': 'Elizabeth Taylor - So Glamorous Cabaret Version',
  'duration_ms': 247268,
  'track_number': 14,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/4UBWugj5D20ZveyzdGpqvD',
  'uri': 'spotify:track:4UBWugj5D20ZveyzdGpqvD',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '0Ny2HkSrLtvmBVwCQywyip',
  'song_name': 'Opalite - Life Is A Song Acoustic Version',
  'duration_ms': 242738,
  'track_number': 15,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/0Ny2HkSrLtvmBVwCQywyip',
  'uri': 'spotify:track:0Ny2HkSrLtvmBVwCQywyip',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '2JHzTARFUispsjZHKhrxxO',
  'song_name': 'Eldest Daughter - Now You’re Home Acoustic Version',
  'duration_ms': 244363,
  'track_number': 16,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/2JHzTARFUispsjZHKhrxxO',
  'uri': 'spotify:track:2JHzTARFUispsjZHKhrxxO',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6hKfPNnVlA2cgTgKj6Vgcw',
  'song_name': 'Ruin The Friendship - My Advice Version',
  'duration_ms': 222087,
  'track_number': 17,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/6hKfPNnVlA2cgTgKj6Vgcw',
  'uri': 'spotify:track:6hKfPNnVlA2cgTgKj6Vgcw',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1qwClaxDb5fCrLjXaAmB35',
  'song_name': 'Wi$h Li$t - Settled Down Acoustic Version',
  'duration_ms': 210912,
  'track_number': 18,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/1qwClaxDb5fCrLjXaAmB35',
  'uri': 'spotify:track:1qwClaxDb5fCrLjXaAmB35',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '2DF2sUvgHFKJ5TQGjm6n3T',
  'song_name': 'The Life of a Showgirl (feat. Sabrina Carpenter) - Dressing Room Rehearsal Version',
  'duration_ms': 239790,
  'track_number': 19,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/2DF2sUvgHFKJ5TQGjm6n3T',
  'uri': 'spotify:track:2DF2sUvgHFKJ5TQGjm6n3T',
  'album_id': '6QNMhoV8V0u7cFuhhUBOn7',
  'album_name': 'The Life of a Showgirl + Acoustic Collection',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '53iuhJlwXhSER5J2IYYv1W',
  'song_name': 'The Fate of Ophelia',
  'duration_ms': 226073,
  'track_number': 1,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/53iuhJlwXhSER5J2IYYv1W',
  'uri': 'spotify:track:53iuhJlwXhSER5J2IYYv1W',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1jgTiNob5cVyXeJ3WgX5bL',
  'song_name': 'Elizabeth Taylor',
  'duration_ms': 208291,
  'track_number': 2,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/1jgTiNob5cVyXeJ3WgX5bL',
  'uri': 'spotify:track:1jgTiNob5cVyXeJ3WgX5bL',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '3yWuTOYDztXjZxdE2cIRUa',
  'song_name': 'Opalite',
  'duration_ms': 235355,
  'track_number': 3,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/3yWuTOYDztXjZxdE2cIRUa',
  'uri': 'spotify:track:3yWuTOYDztXjZxdE2cIRUa',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '03bTIHJElXZ0O0jqOQvAbY',
  'song_name': 'Father Figure',
  'duration_ms': 212777,
  'track_number': 4,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/03bTIHJElXZ0O0jqOQvAbY',
  'uri': 'spotify:track:03bTIHJElXZ0O0jqOQvAbY',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '62HoDY1Km6lm47haFpUn9c',
  'song_name': 'Eldest Daughter',
  'duration_ms': 246356,
  'track_number': 5,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/62HoDY1Km6lm47haFpUn9c',
  'uri': 'spotify:track:62HoDY1Km6lm47haFpUn9c',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '62V2ZHslgQV98gH4AuVXnr',
  'song_name': 'Ruin The Friendship',
  'duration_ms': 220564,
  'track_number': 6,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/62V2ZHslgQV98gH4AuVXnr',
  'uri': 'spotify:track:62V2ZHslgQV98gH4AuVXnr',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '2x3mwb96B6TquRqMtbxUE1',
  'song_name': 'Actually Romantic',
  'duration_ms': 163699,
  'track_number': 7,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/2x3mwb96B6TquRqMtbxUE1',
  'uri': 'spotify:track:2x3mwb96B6TquRqMtbxUE1',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '2TEQvxxQabwLQMqWMg1qGu',
  'song_name': 'Wi$h Li$t',
  'duration_ms': 207349,
  'track_number': 8,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/2TEQvxxQabwLQMqWMg1qGu',
  'uri': 'spotify:track:2TEQvxxQabwLQMqWMg1qGu',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '5ylJtmaWPJ33cW3En7WOu0',
  'song_name': 'Wood',
  'duration_ms': 150517,
  'track_number': 9,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/5ylJtmaWPJ33cW3En7WOu0',
  'uri': 'spotify:track:5ylJtmaWPJ33cW3En7WOu0',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1appZ3c336FkPvCuywfmrs',
  'song_name': 'CANCELLED!',
  'duration_ms': 211498,
  'track_number': 10,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/1appZ3c336FkPvCuywfmrs',
  'uri': 'spotify:track:1appZ3c336FkPvCuywfmrs',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '4qmFC3Jz5aQ0erlk2OSi2X',
  'song_name': 'Honey',
  'duration_ms': 181534,
  'track_number': 11,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/4qmFC3Jz5aQ0erlk2OSi2X',
  'uri': 'spotify:track:4qmFC3Jz5aQ0erlk2OSi2X',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '5eXgqtg3T8Av0m1FUaGHex',
  'song_name': 'The Life of a Showgirl (feat. Sabrina Carpenter)',
  'duration_ms': 241766,
  'track_number': 12,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/5eXgqtg3T8Av0m1FUaGHex',
  'uri': 'spotify:track:5eXgqtg3T8Av0m1FUaGHex',
  'album_id': '4a6NzYL1YHRUgx9e3YZI6I',
  'album_name': 'The Life of a Showgirl',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '0yZPIEgco572UWiwoQtcYF',
  'song_name': 'The Life of a Showgirl Intro',
  'duration_ms': 4947,
  'track_number': 1,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/0yZPIEgco572UWiwoQtcYF',
  'uri': 'spotify:track:0yZPIEgco572UWiwoQtcYF',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '5k9RjjuYyOMCLL81U8FaHT',
  'song_name': 'The Fate of Ophelia - Track by Track',
  'duration_ms': 41648,
  'track_number': 2,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/5k9RjjuYyOMCLL81U8FaHT',
  'uri': 'spotify:track:5k9RjjuYyOMCLL81U8FaHT',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1dosSsKwYF7hoQA2kuu6wI',
  'song_name': 'The Fate of Ophelia',
  'duration_ms': 226073,
  'track_number': 3,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/1dosSsKwYF7hoQA2kuu6wI',
  'uri': 'spotify:track:1dosSsKwYF7hoQA2kuu6wI',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '3r9fAceWmaDFvbNiTnFiLr',
  'song_name': 'Elizabeth Taylor - Track by Track',
  'duration_ms': 35910,
  'track_number': 4,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/3r9fAceWmaDFvbNiTnFiLr',
  'uri': 'spotify:track:3r9fAceWmaDFvbNiTnFiLr',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1A2vZKJZovt4828jwLgiB3',
  'song_name': 'Elizabeth Taylor',
  'duration_ms': 208291,
  'track_number': 5,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/1A2vZKJZovt4828jwLgiB3',
  'uri': 'spotify:track:1A2vZKJZovt4828jwLgiB3',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '5SkuikJwvwfEvNyCepGkq3',
  'song_name': 'Opalite - Track by Track',
  'duration_ms': 44594,
  'track_number': 6,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/5SkuikJwvwfEvNyCepGkq3',
  'uri': 'spotify:track:5SkuikJwvwfEvNyCepGkq3',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '67osB3wmJVTFzKhWqPb1Hm',
  'song_name': 'Opalite',
  'duration_ms': 235356,
  'track_number': 7,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/67osB3wmJVTFzKhWqPb1Hm',
  'uri': 'spotify:track:67osB3wmJVTFzKhWqPb1Hm',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '2NGGvVcfb2m2NbVaXHC3gb',
  'song_name': 'Father Figure - Track by Track',
  'duration_ms': 32838,
  'track_number': 8,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/2NGGvVcfb2m2NbVaXHC3gb',
  'uri': 'spotify:track:2NGGvVcfb2m2NbVaXHC3gb',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '1lD0oPIfSYid1LhPvgrz10',
  'song_name': 'Father Figure',
  'duration_ms': 212777,
  'track_number': 9,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/1lD0oPIfSYid1LhPvgrz10',
  'uri': 'spotify:track:1lD0oPIfSYid1LhPvgrz10',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '0wAvTNz81YTUhLFWuWJSAV',
  'song_name': 'Eldest Daughter - Track by Track',
  'duration_ms': 51818,
  'track_number': 10,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/0wAvTNz81YTUhLFWuWJSAV',
  'uri': 'spotify:track:0wAvTNz81YTUhLFWuWJSAV',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6iC3L3YmAkGucvJbXKDanA',
  'song_name': 'Eldest Daughter',
  'duration_ms': 246356,
  'track_number': 11,
  'disc_number': 1,
  'explicit': True,
  'spotify_url': 'https://open.spotify.com/track/6iC3L3YmAkGucvJbXKDanA',
  'uri': 'spotify:track:6iC3L3YmAkGucvJbXKDanA',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},
 {'song_id': '6NUy8xajng5zMSGJRKniAG',
  'song_name': 'Ruin The Friendship - Track by Track',
  'duration_ms': 40746,
  'track_number': 12,
  'disc_number': 1,
  'explicit': False,
  'spotify_url': 'https://open.spotify.com/track/6NUy8xajng5zMSGJRKniAG',
  'uri': 'spotify:track:6NUy8xajng5zMSGJRKniAG',
  'album_id': '4tFsJC9jQ0Qjj7HSExhAdm',
  'album_name': 'The Life of a Showgirl (Track by Track Version)',
  'artist_id': '06HL4z0CvFAxyc27GXpf02',
  'artist_name': 'Taylor Swift'},

In [34]:
song_df = pd.DataFrame(song_list)
song_df.head()

,song_id,song_name,duration_ms,track_number,disc_number,explicit,spotify_url,uri,album_id,album_name,artist_id,artist_name
0,5UQ3JrA9kEh7rfwhUS1h0z,The Fate of Ophelia,226073,1,1,False,https://open.spotify.com/track/5UQ3JrA9kEh7rfw...,spotify:track:5UQ3JrA9kEh7rfwhUS1h0z,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,06HL4z0CvFAxyc27GXpf02,Taylor Swift
1,6virCtlwc98cKYVyeZYXqq,Elizabeth Taylor,208291,2,1,False,https://open.spotify.com/track/6virCtlwc98cKYV...,spotify:track:6virCtlwc98cKYVyeZYXqq,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,06HL4z0CvFAxyc27GXpf02,Taylor Swift
2,0WUwHkIXQY55MLOrw8EM6m,Opalite,235356,3,1,False,https://open.spotify.com/track/0WUwHkIXQY55MLO...,spotify:track:0WUwHkIXQY55MLOrw8EM6m,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,06HL4z0CvFAxyc27GXpf02,Taylor Swift
3,6H0nEKqkTRxa30Pru1h7SD,Father Figure,212777,4,1,True,https://open.spotify.com/track/6H0nEKqkTRxa30P...,spotify:track:6H0nEKqkTRxa30Pru1h7SD,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,06HL4z0CvFAxyc27GXpf02,Taylor Swift
4,6nhsv9Jeluz5gXt592KN3m,Eldest Daughter,246356,5,1,True,https://open.spotify.com/track/6nhsv9Jeluz5gXt...,spotify:track:6nhsv9Jeluz5gXt592KN3m,6QNMhoV8V0u7cFuhhUBOn7,The Life of a Showgirl + Acoustic Collection,06HL4z0CvFAxyc27GXpf02,Taylor Swift

In [35]:
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 393 entries, 0 to 392
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   song_id       393 non-null    str
 1   song_name     393 non-null    str
 2   duration_ms   393 non-null    int64
 3   track_number  393 non-null    int64
 4   disc_number   393 non-null    int64
 5   explicit      393 non-null    bool
 6   spotify_url   393 non-null    str
 7   uri           393 non-null    str
 8   album_id      393 non-null    str
 9   album_name    393 non-null    str
 10  artist_id     393 non-null    str
 11  artist_name   393 non-null    str
dtypes: bool(1), int64(3), str(8)
memory usage: 34.3 KB

In [36]:
#converting duration from ms to seconds for readability
song_df['duration_ms'] = (song_df['duration_ms']/1000).round(2)

In [38]:
song_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 393 entries, 0 to 392
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   song_id       393 non-null    str
 1   song_name     393 non-null    str
 2   duration_ms   393 non-null    float64
 3   track_number  393 non-null    int64
 4   disc_number   393 non-null    int64
 5   explicit      393 non-null    bool
 6   spotify_url   393 non-null    str
 7   uri           393 non-null    str
 8   album_id      393 non-null    str
 9   album_name    393 non-null    str
 10  artist_id     393 non-null    str
 11  artist_name   393 non-null    str
dtypes: bool(1), float64(1), int64(2), str(8)
memory usage: 34.3 KB

In [39]:
song_df.isnull().sum()

song_id         0
song_name       0
duration_ms     0
track_number    0
disc_number     0
explicit        0
spotify_url     0
uri             0
album_id        0
album_name      0
artist_id       0
artist_name     0
dtype: int64